name: Download Chrome Extension

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: sc-chrome-plugin
          path: ${{ github.workspace }}/sc-chrome-plugin/
          if-no-files-found: error
          retention-days: 30